### ISSUE TITLE
Edit or delete a past event

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#105]
## Problem description
It's not possible to edit or delete a past event. It could be useful if you want to revert a metered unit that you don't want to take into account

**Comment by mtews** [comment]
This sounds a bit dangerous to me, such features should be handled with a lot of care at the very least. I think we want to have a system that is 100% tamper-proof and 100% audit-proof at all times (as long as it is in production), but as long as that remains provided...

**Comment by corvus-ch** [comment]
In an ideal world, where software does not have bugs and people do not make mistakes, yes, that feature would not be needed. However, this is not utopia and errors are being made and needs to be fixed after the fact.

At VSHN AG, we extract our events from a Prometheus API (actually Thanos, with a retention of two years → https://kb.vshn.ch/appuio-cloud/references/quality-requirements/functional/invoicing-retention.html). This gives us the ability, to replay billing based on that data. We have had to do that, because the Prometheus queries used were wrong and needed to be updated. So far, we never did so for the past month (monthly invoicing) but only for the current running month.

**Comment by michaelponrajah** [comment]
Hey @mtews & @corvus-ch, 

We're gathering all feature request in a new tool. I'll archive this issue but feel free to follow the discussion, add your feedback for the team and vote here
👉 [Edit delete past events](https://getlago.canny.io/feature-requests/p/edit-delete-past-events)
