### ISSUE TITLE
[FEAT]: invoice approvals

### ISSUE THREAD

**Issue by derekperkins** [getlago/lago#122]
**Is your feature request related to a problem? Please describe.**
For larger invoices or invoices with excessive overage, we would like for those to go through a manual approval process.

**Describe the solution you'd like**
Have all invoices be generated in a pending state. We would listen for the invoice created webhook, and then have some rules on our side to auto-approve or forward to accounting for manual approval. Only after approval would the invoice be closed, card charged, and emails sent.

**Describe alternatives you've considered**
From what I can tell, there's no way to halt the invoice flow

**Additional context**
At invoice time, we also like to run some manual checks against our usage tables to make sure that what we have matches what is in Lago, and if there are any discrepancies, we would delete the prior usage and update with the new usage. This doesn't happen often, but it's also going to happen where there is some late-arriving or otherwise incorrect data after the initial usage reporting

**Related issues**
- #105 
- #67

**Comment by derekperkins** [comment]
cc @mordfustang21

**Comment by mathieu-lago** [comment]
Hi @derekperkins - thanks for your time earlier!

Quick summary in case other people are interested in this feature: we're currently working on grace periods, which will allow users to review the invoices before they are sent to customers. Ideally, you'd like the Finance team to review the invoices and approve them manually via the user interface.

The first version of the feature will allow users to define a grace period after which all invoices are automatically approved, but the manual check is something we could add as part of the next iteration.

#99

**Comment by michaelponrajah** [comment]
Hey @derekperkins, as Mathieu mentioned above, we've released the feature `Grace period` allowing users to define a number of days where the invoice is in Draft status after the end of a billing period in order to manual check it. 

Invoices can be finalized once the number of days is over or you can also finalize it manually through the User Interface or the API.

Please find more information about [this feature here](https://doc.getlago.com/docs/guide/invoicing/grace-period)
