### ISSUE TITLE
[FEAT]: Set first day of the week

### ISSUE THREAD

**Issue by omar2205** [getlago/lago#167]
**Is your feature request related to a problem? Please describe.**
You can't set the first day of the week, it's presumed Monday.

**Describe the solution you'd like**
More control of the timezone and Week calendar.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1373867/209723574-41ad86ec-ad0c-4875-966b-61ba6d2f1a72.png)

World map showing the first day of the week used in different countries

🟨  Monday
🟥  Friday
🟩  Saturday
🟦  Sunday

**Comment by mathieu-lago** [comment]
Hi @omar2205 - thanks for reaching out! That's a good point, which is why we've started working on a feature that will allow users to align the billing cycle with the customer's timezone: https://github.com/getlago/lago/issues/146

However, this feature will not allow you to set the first day of the week, so that's an improvement for a future version.

**Comment by mathieu-lago** [comment]
Logged here: https://getlago.canny.io/feature-requests/p/define-whats-the-first-day-of-the-week
