### ISSUE TITLE
[BUG]: docker run on aliyun with internal ip, front page report: blocked by CORS policy

### ISSUE THREAD

**Issue by kerry999** [getlago/lago#201]
**Describe the bug**

lago docker is deployed in aliyun(centos) server, which has internal ip (e.g 192.168.1.2 ) and public ip (e.g 100.100.100.1).
configure the docker by .env:
(assume my public web url is my.web.com.cn )

LAGO_API_URL="http://my.web.com.cn:3000"
LAGO_PDF_URL="http://my.web.com.cn:3000"
API_PORT=3000
LAGO_FRONT_URL="http://my.web.com.cn"
FRONT_PORT=80

open the front in http://my.web.com.cn/login,  the login page displayed with a warning message: "an error occured, please reload the application"

the console report error:
login:1 
        
       Access to fetch at 'http://my.web.com.cn:3000/graphql' from origin 'http://my.web.com.cn' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**To Reproduce**
i had tried configure the 
LAGO_FRONT_URL="http://my.web.com.cn" or 
LAGO_FRONT_URL="http://192.168.1.2" or
LAGO_FRONT_URL="http://localhost"

all failed with same error. 

i also tried configure nginx to add Access-Control-Allow-Origin header.  but it also doesn't help.

=================
server {
        listen       8081;
        listen       [::]:8081;
        server_name  my.web.com.cn;
        root         /usr/share/nginx/html;

        location / {
            proxy_pass http://192.168.1.2:80;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            #imple requests
            if ($request_method ~* "(GET|POST)") {
              add_header "Access-Control-Allow-Origin"  *;
            }

            # Preflighted requests
            if ($request_method = OPTIONS ) {
              add_header "Access-Control-Allow-Origin"  *;
              add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
              add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";
              return 200;
            }
        }
....
==================

**Expected behavior**
the login page run without error.

**Screenshots**
If applicable, add screenshots to help explain your [problem.]

**Support**
 - OS: 
Linux devserver 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux, 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
 - Browser edge
 - Version lastest main version on Jan.27 2023

**Additional context**
![Screenshot lago login page error](https://user-images.githubusercontent.com/16098024/221419584-e600326e-2ced-4a38-9e8b-1c1fed12ddf1.png)

**Comment by jdenquin** [comment]
Hello @kerry999 

You should define `LAGO_FRONT_URL` to `http://rehabdev.sensfusion.com.cn` according to your screenshot.
This should be defined for the `api` since it has to accept the origin defined by the env var.

You should also check that the `RAILS_ENV` env var is set to `production`

**Comment by kerry999** [comment]
i configured .env as what you suggested. but got same error. 

![Screenshot env](https://user-images.githubusercontent.com/16098024/221571077-c419311c-b650-43fb-acb9-85664288f47f.png)

and i captured tcpdump which shows that the 200 OK response to Http Option package has no Access-Control-Allow-Origin.

![Screenshot tcpdump](https://user-images.githubusercontent.com/16098024/221571416-0f1933fc-5fbe-43eb-888a-e39eab8dbdf5.png)

**Comment by kerry999** [comment]
btw, 172.17.13.106 is internal ip of my server which run on aliyun ( a cloud provider like aws )

**Comment by jdenquin** [comment]
Thanks for the informations!

Could you launch a rails console into your `api` container ? (by running this command in a terminal connected to it `rails console`)
and in this console doing

```shell
irb(main) > ENV['LAGO_FRONT_URL']
```

This should be equal to your URL!

**Comment by LuboNenov** [comment]
Currently, I am having the same issue with the error on login. 
I am using the docker-compose and the rails console returns the same LAGO_FRONT_URL as the one in the .env
<img width="446" alt="image" src="https://user-images.githubusercontent.com/60894956/221898170-d9fad528-53f7-41d5-8262-992697ebab11.png">

And because of that, I found out that I have switched the two URLs (LAGO_FRONT_URL and LAGO_API_URL)
However, it is invoking an Appollo error and not CORS (First I had a cors error because of my domain but I fixed it now).
<img width="446" alt="image" src="https://user-images.githubusercontent.com/60894956/221897355-13c74042-5f9d-4f85-9537-68904f661877.png">

**Comment by jdenquin** [comment]
@LuboNenov do you have this error when accessing to the front end or when you try to login?

**Comment by LuboNenov** [comment]
The error is upon login. 
However, there is another Network error before that you can see the whole situation in this image:

<img width="1435" alt="Screenshot 2023-03-01 at 15 56 50" src="https://user-images.githubusercontent.com/60894956/222161380-744ed758-749e-4dc3-b0f0-27c564e53632.png">

**Comment by LuboNenov** [comment]
I found something interesting, as it turns out Firefox doesn't detect the actual error. When I connected to the front end from safari it tells me that the actual error is a CORS problem again.

<img width="1290" alt="Screenshot 2023-03-01 at 16 42 45" src="https://user-images.githubusercontent.com/60894956/222173561-6fa69913-aa24-45ff-a396-1a07129ac63a.png">

**Comment by kerry999** [comment]
hi Denquin,

sorry for late response, it did take me some time because i don't familiar with docker or rail. correct me if below are wrong.
I run following command to enter console of api:
   sudo docker exec -it lago-api /bin/bash
then, i found rails by 
8f906fc391a9:~# which rails
/usr/local/bundle/bin/rails

but run 'rails console' output usage, it looks like rails has no option of console.
8f906fc391a9:~# rails console
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated engines)
      [--skip-collision-check], [--no-skip-collision-check]  # Skip collision check
  -r, [--ruby=PATH]                                          # Path to the Ruby binary of your choice

**Comment by jdenquin** [comment]
@LuboNenov whats is the url you are accessing the front end? is it the same as the `LAGO_FRONT_URL` ?

@kerry999 can you try `bundle exec rails c` ?

**Comment by kerry999** [comment]
hi Denquin,

please check the output of 'bundle exec rails c' below:

![rails_env](https://user-images.githubusercontent.com/16098024/222406358-f0232f42-fc93-463f-a4ad-de15843fa99a.png)

**Comment by LuboNenov** [comment]
@kerry999 This is the command to go to the rails console ```docker exec -it lago-api bin/rails c```. You don't run bash.

**Comment by LuboNenov** [comment]
> @LuboNenov whats is the url you are accessing the front end? is it the same as the `LAGO_FRONT_URL` ?


Yes it is the same as you can see here:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60894956/222427096-0ff1bfd3-5ad9-4c29-aa7f-c45a885342b4.png">

And this is everything from my .env:

```
FRONT_PORT=8008
LAGO_API_URL="server.bonin.tech:3000"
LAGO_FRONT_URL="server.bonin.tech"
```

Moreover, I am sure the API is working on port 3000 because I get a 401 error (because I cannot access an API token without signing up).

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/60894956/222429068-395a3e84-8151-4066-a892-4d3d21719009.png">

**Comment by jdenquin** [comment]
@kerry999 your `LAGO_FRONT_URL` in the rails console should be the one you defined, it seems it's not taken in account by Docker, I think your issue is around this!

@LuboNenov are you sure that your `LAGO_FRONT_URL` is the good one when you check with the `rails console`, a CORS is coming from this url because the API does not allow the access when it start.

**Comment by kerry999** [comment]
@jdenquin how to fix the wrong LAGO_FRONT_URL? I only modified .env file and run "sudo docker compose up".  are these steps wrong please?

**Comment by kerry999** [comment]
> @kerry999 your `LAGO_FRONT_URL` in the rails console should be the one you defined, it seems it's not taken in account by Docker, I think your issue is around this!
@jdenquin how to fix it please? I did nothing but create a '.env' file as mentions at the begining of this discussion and run "sudo docker compose up" to start the docker.

**Comment by jdenquin** [comment]
you can modify it directly into the `docker-compose.yml` file instead of using the `.env` file just to try it out?

**Comment by kerry999** [comment]
@jdenquin that works! is it a bug of docker which failed to read .env into yml?

**Comment by jdenquin** [comment]
it seems its because docker-compose does not take the `.env` file, maybe you can try to use the `--file` arg

**Comment by LuboNenov** [comment]
I found out what my problem was!
My old .env looked like this as I wrote a few days ago: 
```FRONT_PORT=8008
LAGO_API_URL="server.bonin.tech:3000"
LAGO_FRONT_URL="server.bonin.tech"
```
Well as it turns out the LAGO_FRONT_URL should have the port if it is not port 80 (which is the default one)
So the solution would've been more straightforward if the documentation highlighted that the custom port should be next to the URL.
The final .env looks as follows:
```
FRONT_PORT=8008
LAGO_API_URL="server.bonin.tech:3000"
LAGO_FRONT_URL="server.bonin.tech:8008"
```
Thank you for all the effort you put into my issue @jdenquin
