### ISSUE TITLE
[BUG]: It's not possible to add a dimension value once the Plan is created

### ISSUE THREAD

**Issue by leonardochen** [getlago/lago#247]
**Describe the bug**
In the [Dimensions documentation](https://doc.getlago.com/docs/guide/billable-metrics/dimensions), how do I add a new `provider` such as DigitalOcean? Once the Plan is created and metrics reported, I am unable to modify it to add the new provider.

I was able to manipulate the billable_metric via PUT on the API, but I think once metrics are reported, I'm not able to make any changes.

**To Reproduce**
1. Create new metric with a few values for dimensions/groups
2. Setup a Plan, add a subscription to a customer.
3. Report metrics for the subscription.
4. Try to add a new value to the dimension.

**Expected behavior**
Not all providers will be known when the metric is created. We should be able to add new values.

**Comment by mathieu-lago** [comment]
Hi @leonardochen - thanks for reaching out! This is actually the expected behaviour. Editing dimensions related to charges linked to active subscriptions could have significant impact on the current billing cycle. Therefore, to prevent errors, we decided to disable the "edit" feature.

However, we understand this can be inconvenient, so we will work on an improvement to remove this restriction: https://getlago.canny.io/feature-requests/p/edit-groups-associated-with-billable-metrics
