### ISSUE TITLE
[FEAT]: Allow multiple plans per customer

### ISSUE THREAD

**Issue by jerbob92** [getlago/lago#50]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to assign multiple plans to the same customer, to have a separate plan per product.

**Comment by sarkissianraffi** [comment]
It would be great to dig into this use case with you, to make sure we can create the perfect feature. We already had this request for the cloud version. Do you mind to reach out to raff@getlago.com or hello@getlago.com, so we can plan this?

Thanks a lot

**Comment by jerbob92** [comment]
Thanks! Mathieu contacted me on LinkedIn so I will pick this up with him.

**Comment by sarkissianraffi** [comment]
Hey @jerbob92, closing this issue because this feature is going to be released today.
Here are useful documentation links: 
**- Changelog:** https://doc.getlago.com/changelog/multiple-plans
**- Guide:** https://doc.getlago.com/docs/guide/plans/subscription#multiple-plans 

Hope it will be useful for your use case!
