### ISSUE TITLE
Invoice grace periods and payment grace periods

### ISSUE THREAD

**Issue by sarkissianraffi** [getlago/lago#99]
## Problem description

For now, an invoice and a payment are emitted instantly. Some users want to have a custom delay to trigger them.

**Comment by corvus-ch** [comment]
This is critical for VSHN to adopt Lago.

We collect usage metrics using Prometheus. There is a Prometheus setup in each and every system we operate (Kubernetes/OpenShift). Metrics, relevant for billing, are aggregated into a central data pool using the Thanos tool suite. Invoices are then generated from that central data pool.

Due to the inner workings of that setup, there is a delay of at least two hours until a metric becomes available centrally. So, when canceling a subscription, or when doing the periodical invoice run, creating the invoice must be delayed, so all usage metrics can be taken into account.

**Comment by mathieu-lago** [comment]
https://doc.getlago.com/changelog/grace-period
